name: impaciencia
channels:
  - conda-forge
  - defaults
dependencies:
  - matplotlib
  - tornado=4.5.3
  - notebook
  - opencv
  - pillow
  - requests
  - pip:
    - foxdot
    - pygame
    - srtm.py
